### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ylynfatt** [relwell/DapsBundle#6]
Is there any documentation on how to setup and incorporate this Bundle into an existing Symfony application?

**Comment by relwell** [comment]
@ylynfatt sorry for taking so long to get back to you. There presently isn't, but that's something I could change in the future. You should be able to just use the bundle provided you set the params from the other issue you opened in your application config.

**Comment by ylynfatt** [comment]
@relwell Thanks for replying. It would really appreciate if some documentation could be added. I'm finding it a bit difficult getting the Bundle setup at the moment, especially since I'm relatively new to Symfony. Do I need to remove the AcmeBundle (it seems the DapsLdapBundle depends on some of the templates? Do I need add or change any routes to my general app/config/routing_dev.yml file?

**Comment by relwell** [comment]
That controller is just a remnant from previous rounds of testing, and doesn't really matter.

Please take a look at the [Symfony2 instructions on how to create a custom UserProvider](http://symfony.com/doc/current/cookbook/security/custom_provider.html#modify-security-yml). You'll basically need to register the components provided in this bundle with your application.

**Comment by ylynfatt** [comment]
Thanks @relwell that helped. I've now got it working. I'll submit some initial documentation soon for you to take a look at.
